name: terraform apply

on:
   push:
     branches:
      - 'dev'
     paths:
      - 'live/stage/**'
      - 'website/**'
      - '.github/workflows/**'

jobs:
  TerraformApply:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - 'live/stage/services/website'
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v7
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8
          terraform_wrapper: false
      - name: terraform init
        run: |
          terraform init
      - name: terraform plan
        run: |
          terraform plan -out=tfplan
      - name: terraform apply
        run: |
          terraform apply -auto-approve
      - name: Sync website files
        if: matrix.service == 'live/prod/services/website'
        run: |
          BUCKET=$(terraform output -raw bucket_name)
          aws s3 sync ../../../../website "s3://$BUCKET" --delete