name: terraform apply

on:
   push:
     branches: [dev]
     paths:
      - 'live/stage/**'
      - 'website/**'
      - '.github/workflows/**'
   pull_request:
    branches: [dev]
    paths:
      - 'live/stage/**'
      - 'website/**'
      - '.github/workflows/**'
   workflow_dispatch:

jobs:
  TerraformApply:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - 'live/stage/services/website'
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v7
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8
          terraform_wrapper: false
      - name: terraform init
        run: |
          terraform init
      - name: terraform validate
        run: |
          terraform validate
      - name: trivy iac scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      - name: trivy results to github security
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
      - name: terraform plan
        run: |
          terraform plan -out=tfplan
      - name: terraform apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          terraform apply -auto-approve tfplan
      - name: Sync website files
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && matrix.service == 'live/stage/services/website'
        run: |
          BUCKET=$(terraform output -raw bucket_name)
          aws s3 sync ../../../../website "s3://$BUCKET" --delete